### ISSUE TITLE
Allow different layouts for Multiple Entries and Single Entry

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1177]
Lots of users have requested this functionality. Let's start considering the possibility of doing it. This will allow greater modifications to the way a user can display the single entry page.

Always show the Layout Type metabox as a configuration step, like the Data Source.

-----------

## Requirements

- Must be backward compatible: The default must be the Multiple Entries layout is the layout used for Single Entry.
- Don't get bogged down trying to rework our renderer. Use existing hooks and methods.
- Write unit tests

## In order to implement

We will have to modify the renderer to use different templates based on the context. 

This likely will involve filtering [`gravityview/template/view/class` in `View_Renderer::render()` ](https://github.com/GravityKit/GravityView/blob/f825710332284fd843bff339ba5c7606d28064ce/future/includes/class-gv-renderer-view.php#L100-L108) and [`gravityview/template/entry/class` in `Entry_Renderer::render()`](https://github.com/GravityKit/GravityView/blob/f825710332284fd843bff339ba5c7606d28064ce/future/includes/class-gv-renderer-entry.php#L118-L131).

I think this isn't hard to implement—a day or two for the design, a day or two for the back-end code, and a day or two for writing tests.

**Comment by zackkatz** [comment]
> Lots of users have requested this functionality. Let's start considering the possibility of doing it. This will allow greater modifications to the way a user can display the single entry page.

@rafaehlers Is this request the same as having different layouts for Multiple Entries and Single Entry?

**Comment by rafaehlers** [comment]
@zackkatz Yes, but the opposite can be done with DIY already. So, allowing the Single Entry to be customizable, is the way to go I believe.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1499668565/34162/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1499878734/34166

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2068637078/44848

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2077323604/45091

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2106381129/45970

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2140037649/46652

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1879471744/41188

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2010351635/43507

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2140256980/46657

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2157566585/47065

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2226541838/48603/

**Comment by zackkatz** [comment]
We have a design for this in Figma.

**Comment by zackkatz** [comment]
@doekenorg I'm adding this to your plate, but I'm not sure what priority it should be yet. Let's discuss before you start.

I'm loving what you're doing currently, fixing a bunch of stuff across all the plugins! I'm thinking another few weeks of that and we'll have so much checked off the list!

**Comment by crbdev** [comment]
**Another reason for this**: When using the PDF for GravityView Extension to build custom PDF documents, it's much easier to design/style the Single Entry PDFs using the DIY layout. However, there are times when you may want a simple table for the Multiple Entries layout.

**Comment by floatytheastronaut** [comment]
FreeScout #77242. <br>https://support.gravitykit.com/conversation/77242?folder_id=1

**Comment by doekenorg** [comment]
@doekenorg for todo

**Comment by floatytheastronaut** [comment]
FreeScout #78879. <br>https://support.gravitykit.com/conversation/78879?folder_id=1
