### ISSUE TITLE
Can't edit a Post Custom Field set up as a File Upload field.

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1317]
It's impossible to modify a custom field (from Post Fields) set up as a file upload field on the Edit Entry page of the View.

Some people use this type of field as a File Upload field incorrectly. The value of these fields can't be modified later.

Since: GV 2.3.2

Related: https://docs.gravitykit.com/article/245-editable-post-fields

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/858894028/20772

**Comment by jlgrisham** [comment]
https://secure.helpscout.net/conversation/956031618/22484?folderId=408730

**Comment by soulseekah** [comment]
Okay, how do I setup a custom field as a file upload? What's the merge tag to use?

**Comment by rafaehlers** [comment]
FYI @soulseekah 
![image](https://user-images.githubusercontent.com/1222472/65007343-354aa580-d8dc-11e9-9696-a632f0c1e5fa.png)

this is not a priority though.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1113014338/25916

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1243543460/28402

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1226818641/28060/

**Comment by rajapss** [comment]
I need a small favor, I added a new custom field of the post with a file in my client's gravity form. Also mapped the existing custom_field name for it. When I upload the jpg file from gravity form. Uploaded jpg image is not visible in my post and also it is not visible in the gravity view edit section. Kindly do the needful. Thank You !!

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1898102693/41522/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2134582465/46535

**Comment by rafaehlers** [comment]
Still happening on GV 2.16.6

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2237508934/48858/
