### ISSUE TITLE
Search Bar enhancement: Search by number range

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1426]
Currently, the Search Bar widget allows users to filter entries based on exact matches or predefined criteria. However, for `number`, `product price`, `product quantity`, and `product total amount` fields, having the ability to search within a specific range (from a minimum value to a maximum value) would greatly enhance the UX, especially for directories, real estate listings, or any applications dealing with quantities, measurements, or pricing.

- [x] **UI**: similar to how we currently have it implemented for the "date" field, when a user selects a number or price field to add to the Search Bar, they should have the option to set it as a "range" input type in the View editor. In the frontend, the will be 2 input fields displayed with the `from` and `to` labels.

- [x] **Search logic**: the search should return all entries where the number or price falls inclusively within the specified range. If only the "from" or "to" field is filled out, the search should return all entries greater than or equal to the "from" value, or less than or equal to the "to" value, respectively.

- [x] **Validation and error handling**: Input validation should ensure that users enter valid numbers and that the "from" value is not greater than the "to" value. A validation message should be displayed for invalid inputs.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1095721538/25575/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1197618575/27559?folderId=408730

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1298779840/29568

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1359577901/31181/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1385962205/31666/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1416258769/32376

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1472888337/33618

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1499736457/34164

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1529938243/34864/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1566892148/35658/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1577741666/35875/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1624973659/36793/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1905786792/41630

**Comment by zackkatz** [comment]
https://web.facebook.com/groups/gravitykit/posts/1317639872061634/

**Comment by bennemann** [comment]
https://github.com/gravityview/GravityView/issues/1426

**Comment by floatytheastronaut** [comment]
FreeScout #76378. <br>https://support.gravitykit.com/conversation/76378?folder_id=1

**Comment by floatytheastronaut** [comment]
FreeScout #78338. <br>https://support.gravitykit.com/conversation/78338?folder_id=1

**Comment by rafaehlers** [comment]
Users notified ✅
