### ISSUE TITLE
\GravityView_View::getInstance()->getViewId() isn't being set in single entry

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#1437]
Happens on either View CPT or embedded. Visit a single entry, and `\GravityView_View::getInstance()->getViewId()` will return `0`.

I don't know why `setViewId()` isn't being run.

My current theory is that `template_redirect` (when the `$post` title tag is modified) happens too soon, and `add_action( 'gravityview/loaded', array( $this, 'include_legacy_frontend' ) );` isn't run yet.

The Entry not being set was the cause of #1435, and the Entry wansn't set because the View ID wasn't set. This commit caused the chain reaction: 50c7f072e

@soulseekah Are you able to help us, Obi-Wan Kenobi!?

Related to: https://github.com/gravityview/GravityView/commit/60c622aa46f6c7d8ae58b7df0d584e833ceccd27#diff-1eb5447c4e60ca0fe6bea1ce774689a2L709

----

**Comment by soulseekah** [comment]
The legacy API is updates via `Legacy_Context::push` and `Legacy_Context::load`.

For single entries the context is pushed for the first time during `GV\Entry_Renderer::render` which is spawned via `the_content` filter for the page. So we're definitely a bit late to set anything before the content based on legacy context.

![image](https://user-images.githubusercontent.com/685880/80308701-046b1100-87d9-11ea-873a-40bc6b7ab827.png)

The whole point of `\GravityView_View::getInstance()->getViewId()` was a back-compatibility attempt when `$view` was not being passed in and never tested. So I'm not surprised it didn't work :)

`the_content` and later will work. Anything earlier needs to use the 2.0 API (`gravityview()->view` maybe, etc.) and should be investigated on a case-by-case basis.

**Comment by zackkatz** [comment]
This is largely addressed by #1834. Also, we're going to be working on full 1.x deprecation soon, so we'll address any remaining issues at that time.
