### ISSUE TITLE
Add support for embedding with WooCommerce Account Pages

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#1451]
Customers have reported that Edit Entry functionality for Views embedded in WooCommerce Account Pages don't work properly.

Iconic support says:

> Unfortunately, I don't have a solution, but I do have an idea what's causing the issue.
> 
> My plugin generates endpoints and doesn't use an official WP page to display content. I believe the fact that it is an endpoint is what's causing the issue. Have you tested GravityView when used on a custom endpoint?

[See login to download WooCommerce Account Pages](https://docs.gravityview.co/article/343-logins)

Related to #946, #1524, #939

Ehlers: Here's a possible workaround for this issue: https://docs.gravitykit.com/article/845-embedding-the-edit-entry-form-into-a-page-or-post

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/581890986/14679/

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/604599968/15519/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1201271900/27645/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1456690614/33269/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1715404789/38437/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1865065780/40994/

**Comment by zackkatz** [comment]
FreeScout #71398. <br>https://support.gravitykit.com/conversation/71398?folder_id=1

**Comment by zackkatz** [comment]
FreeScout #72012. <br>https://support.gravitykit.com/conversation/72012?folder_id=1

**Comment by zackkatz** [comment]
FreeScout #72510. <br>https://support.gravitykit.com/conversation/72510?folder_id=1

**Comment by rafaehlers** [comment]
This issue is only related to the WooCommerce Account Pages plugin.

**Comment by rafaehlers** [comment]
Released on 2.18.7 https://github.com/GravityKit/GravityView/releases/tag/v2.18.7
