### ISSUE TITLE
Entry not found during "delete" action when custom slugs are used

### ISSUE THREAD

**Issue by pawelkmpt** [GravityKit/GravityView#1636]
**Describe the Issue**

It is not possible to delete an entry on the frontend when custom slugs are used.

Source of the issue is located in following line:
 https://github.com/gravityview/GravityView/blob/38f864bbd1f7fe0e52e3137ce881d7e73810c6c1/includes/extensions/delete-entry/class-delete-entry.php#L365

My suggested solution:

```diff
- $entry = gravityview_get_entry( $entry_slug, true, false, $view );
+ $entry = gravityview_get_entry( $entry_slug, false, false, $view );
```

2nd param in `gravityview_get_entry()` set to `true` makes `GVCommon::get_entry_id()` return custom slug instead of just ID...

https://github.com/gravityview/GravityView/blob/38f864bbd1f7fe0e52e3137ce881d7e73810c6c1/includes/class-common.php#L662-L666

...and later that slug is passed to `GFAPI::get_entry()` 

https://github.com/gravityview/GravityView/blob/38f864bbd1f7fe0e52e3137ce881d7e73810c6c1/includes/class-common.php#L696

which returns an error.

--------

### Additional information

**This issue happens in the following settings:**

_Please try to re-create the issue in each rendering mode. This helps debug the problem._

- [ ] View
- [x] Embedded via shortcode
- [ ] Embedded via oEmbed

**If shortcode, paste the shortcode below**

`[gravityview id='104']`

**Are Advanced Filter filters configured for the View?**

- [ ] Yes
- [x] No

**If yes, please drag a screenshot below:**

**Comment by rafaehlers** [comment]
@pawelkmpt this should have been fixed on GravityView 2.11: https://github.com/gravityview/GravityView/issues/1606
Which version are you using?

**Comment by pawelkmpt** [comment]
@rafaehlers I'm using 2.12

**Comment by rafaehlers** [comment]
Tested with GV 2.19.3, and it's working: https://www.loom.com/share/5dedf5f709824354b71658d696aed256
