### ISSUE TITLE
Entry link field appears in Single Entry context

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#1654]
**Describe the Issue**

1. Edit a View
2. Click on Single Entry tab
3. Add a field to the layout
4. Search for "link to entry"

What happens:
"Link to Single Entry" field appears

What should happen:
It shouldn't appear because it should only show in Multiple Entries context.

![](https://i.gravityview.co/zr3alq+)

**Comment by rafaehlers** [comment]
Still happening on GV 2.14.4

![image](https://user-images.githubusercontent.com/1222472/167892135-7c5dbcd0-22a0-4c95-b84d-bb7da3a8f7ab.png)

**Comment by rafaehlers** [comment]
Doesn't happen anymore on 2.19.3
