### ISSUE TITLE
Suggestion: Entry Approval via link

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1663]
>Please consider adding entry approval/rejection links that could be sent in email notifications. The user would simply have to click on the link to approve or reject the entry submission or update. He/she would not have to log into the website, visit the page with the View, and perform the action. This would streamline a lot of things.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1724877519/38604/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1777026293/39525/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1810599762/40118/

**Comment by asincariov** [comment]
FreeScout #1050 - Re: Extensions showing as not active on Wordpress (Support Form). https://support.gravitykit.com/conversation/1050?folder_id=1

**Comment by rafaehlers** [comment]
Already implemented: https://docs.gravitykit.com/article/904-entry-moderation-merge-tags
