### ISSUE TITLE
Edit Entry: Usability issue with File Upload and required fields.

### ISSUE THREAD

**Issue by bennemann** [GravityKit/GravityView#1695]
Context: The Edit Entry screen with any required field and a file upload field.

If the user selects a file and submits the form while a required field is empty, the update will fail (as expected). 

However, when the page reloads, the file upload input **isn't cleared**. 

That leads to confusion as the file isn't available anymore and must be uploaded again to be saved:
https://monosnap.com/direct/YbEjhxEoccpX2Kn7ePErSTEWBKreQX

The issue can be reproduced here:
https://debug.gravityview.co/blog/view/required-field-and-file-upload/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1880675598/41208

**Comment by rafaehlers** [comment]
Closed as a dupe of https://github.com/GravityKit/GravityView/issues/853
