### ISSUE TITLE
Edit Link is sometimes incorrectly hidden for shortcode with merge tags due to static cache

### ISSUE THREAD

**Issue by soulseekah** [GravityKit/GravityView#1725]
Okay, so you're gonna laugh, but code I wrote 3 years ago has an apparent bug.

https://github.com/gravityview/GravityView/commit/00b1253ed75279bd3a90e5eb51d69b7f0ad7f746

Whether the edit link is shown or not is cached. And that sometimes is a problem.

--------

### Additional information

1. Create a simple form, View to go with it.
2. Login as a user and fill in the form. Save.
3. Set the View to show Edit Links for submitters.
4. Check View - all good. Edit Link shows for the submitter.
5. Add a shortcode to a page `[gravityview id="5" search_field="created_by" search_value="{user:ID}"]`
6. Edit Links are missing there!

_Please try to re-create the issue in each rendering mode. This helps debug the problem._

- [ ] View
- [x] Embedded via shortcode
- [ ] Embedded via oEmbed

**If shortcode, paste the shortcode below**

`[gravityview id="5" search_field="created_by" search_value="{user:ID}"]`

**Are Advanced Filter filters configured for the View?**

- [ ] Yes
- [x] No

**If yes, please drag a screenshot below:**

# Why is this happening?

So when the shortcode gets parsed by `GravityView_frontend::parse_content` it's not parsing the filters inside it correctly. A call to `$view->get_entries()` at that stage returns 0 entries. As `GravityView_Edit_Entry::maybe_not_visible` is called in chain it will set Edit Links visibility to false! AND CACHE IT.

When the shortcode itself is rendered, the filter returns 1 entry. But it's too late, `maybe_not_visible` returns false from the static cache (`$visibility_cache_for_view`). Ugh.

I'm not exactly sure why `parse_content` isn't filtering correctly. Could be that it's not seeing the merge tag?

# Fix Ideas

Ideally caching in there should only happen based on View parameters. If the parameters change (`parse_content` vs `do_shortcode`) the cache should be aware of this.

Although I would assume that not caching Views with 0 entries would also work.

I think it's important to find out why `parse_content` is returning a View with zero entries as well. Had it been ignoring filtering in the shortcode then all the entries would show. Read this again: ALL ENTRIES would show an edit link :) not only own entries.

This needs a rework.

**Comment by rafaehlers** [comment]
Same here: https://github.com/gravityview/GravityView/issues/1537

**Comment by soulseekah** [comment]
> Same here: https://github.com/gravityview/GravityView/issues/1537

That's it! Merge tags don't seem to be altering the View settings initially getting 0 entries. We just need to figure out the proper fix now.

Sorry for the duplicate. I did search a bit but didn't get any results for "edit entry link", eek. The same caching mechanism is in delete and duplicate, confirmed.

**Comment by soulseekah** [comment]
By the way, here's a snippet that fixes the issue temprorarily suppressing visiblity caching:

```php
/**
 * Add uncached version of GravityView_Edit_Entry::maybe_not_visible
 */
add_action( 'gravityview/field/is_visible', function( $visible, $field, $view ) {
	remove_action( 'gravityview/field/is_visible', [ GravityView_Edit_Entry::getInstance(), 'maybe_not_visible' ], 10, 3 );
	add_action( 'gravityview/field/is_visible', function( $visible, $field, $view ) {
		if ( 'edit_link' !== $field->ID ) {
			return $visible;
		}

		if ( ! $view instanceof \GV\View ) {
			return $visible;
		}

		foreach ( $view->get_entries()->all() as $entry ) {
			if ( GravityView_Edit_Entry::check_user_cap_edit_entry( $entry->as_entry(), $view ) ) {
				return true;
			}
		}
		return false;
	}, 10, 3 );
	return $visible;
}, 9, 3 );
```

This works for Edit only, Delete and Duplicate would need a couple of changes in the class names and the bodies.

**Comment by soulseekah** [comment]
For delete:

``
/**
 * Add uncached version of GravityView_Delete_Entry::maybe_not_visible
 */
add_action( 'gravityview/field/is_visible', function( $visible, $field, $view ) {
	remove_action( 'gravityview/field/is_visible', [ GravityView_Delete_Entry::getInstance(), 'maybe_not_visible' ], 10, 3 );
	add_action( 'gravityview/field/is_visible', function( $visible, $field, $view ) {
		if ( 'delete_link' !== $field->ID ) {
			return $visible;
		}

		if ( ! $view instanceof \GV\View ) {
			return $visible;
		}

		foreach ( $view->get_entries()->all() as $entry ) {
			if ( GravityView_Delete_Entry::check_user_cap_delete_entry( $entry->as_entry(), $view ) ) {
				return true;
			}
		}
		return false;
	}, 10, 3 );
	return $visible;
}, 9, 3 );
```

And duplicate:

```
/**
 * Add uncached version of GravityView_Duplicate_Entry::maybe_not_visible
 */
add_action( 'gravityview/field/is_visible', function( $visible, $field, $view ) {
	remove_action( 'gravityview/field/is_visible', [ GravityView_Duplicate_Entry::getInstance(), 'maybe_not_visible' ], 10, 3 );
	add_action( 'gravityview/field/is_visible', function( $visible, $field, $view ) {
		if ( 'duplicate_link' !== $field->ID ) {
			return $visible;
		}

		if ( ! $view instanceof \GV\View ) {
			return $visible;
		}

		foreach ( $view->get_entries()->all() as $entry ) {
			if ( GravityView_Duplicate_Entry::check_user_cap_duplicate_entry( $entry->as_entry(), $view ) ) {
				return true;
			}
		}
		return false;
	}, 10, 3 );
	return $visible;
}, 9, 3 );
```

**Comment by zackkatz** [comment]
@rafaehlers Please test and see if this is fixed in `develop`.

**Comment by rafaehlers** [comment]
@zackkatz I tested with this latest commit: https://github.com/gravityview/GravityView/commit/94159d289b0e41453ad2a55ae913ecfb925d1d10 and it's still happening.

Video: https://www.loom.com/share/280b23cd684f45c7a0cc99f8b7549644

**Comment by zackkatz** [comment]
@rafaehlers Please test again ;-)
