### ISSUE TITLE
Conflict between GravityView and WooCommerce 'My Account' endpoints

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1735]
When the site homepage is set to the `My Account` page of WooCommerce, the `Orders` endpoint will point to https://debug.gravityview.co/orders/ 

Trying to access that page/endpoint won't work if GravityView is enabled. It will redirect that URL back to the homepage of the website: https://debug.gravityview.co/

Disabling GravityView makes that page accessible: https://debug.gravityview.co/orders/ or setting up another homepage, then https://debug.gravityview.co/my-account/orders/ will work.

![image](https://user-images.githubusercontent.com/1222472/179116711-81ff7ecf-1396-450b-8337-486a0e76e079.png)

![image](https://user-images.githubusercontent.com/1222472/179116440-75a56532-b3d4-4955-900c-c36956f334f6.png)

That will break all these endpoints:

![image](https://user-images.githubusercontent.com/1222472/179116505-58305a4c-bddf-42f0-885c-5c3c5d5bb227.png)

https://user-images.githubusercontent.com/1222472/179116644-c2b5f5bc-08ae-412c-8465-3fcd46a44d3f.mp4

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1946178123/42415/

**Comment by rafaehlers** [comment]
Re: https://github.com/gravityview/GravityView/issues/1451

**Comment by zackkatz** [comment]
FreeScout #72523. <br>https://support.gravitykit.com/conversation/72523?folder_id=1

**Comment by rafaehlers** [comment]
This is a very edge case. As mentioned in the issue, if a My Account page is appropriately set up, then GravityView works completely. I tested it. I am closing to avoid further confusion.

Let's not add more tickets here if they are not explicitly related to this issue.
