### ISSUE TITLE
Implement a `Download CSV` widget 

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1758]
Here's the idea: a widget that can be added to the View to make it easier to export CSVs from the View

![image](https://user-images.githubusercontent.com/1222472/196285333-5cea27f4-f02a-4678-81ef-4a24d69cb966.png)

Currently, we need to teach users how to do that, which is no good: https://docs.gravitykit.com/article/491-csv-export

We can use Dashicons on the button: https://developer.wordpress.org/resource/dashicons/#database-export

Also, the Widget needs to pay attention to the View Settings regarding CSV export permissions and if a Search Bar is present or not. In case there's a Search Bar; usually, the link to the `/csv/` must carry the same search parameters.

**Comment by rafaehlers** [comment]
+1

**Comment by zackkatz** [comment]
Closing in favor of #1891
