### ISSUE TITLE
Entry links (single, edit, duplicate, and go back) are not carrying search parameters

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1776]
This [doc was created ](https://docs.gravitykit.com/article/892-modifying-the-go-back-link-to-avoid-losing-search-parameters), but it shouldn't be necessary because we have the [following filter](https://github.com/gravityview/GravityView/blob/develop/includes/class-api.php#L706): `gravityview/entry_link/add_query_args` since GV 2.10.

For some reason, it's not working on GV 2.15.

**Comment by zackkatz** [comment]
This is caused by `GravityView_Widget_Search::add_reserved_args( $args )`, but I'm not sure what the thinking was for how it currently is set up. Needs further research.
