### ISSUE TITLE
The `[gravityview]` shortcode doesn't work when embedded inside an ACF wysiwyg block

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1812]
A customer reported a time-out issue:

```
I tried setting up a multiple entries layout at https://www.example.com/events-new – the fields included title, start date, end date, image, intro text, single page link. Instead, it is only showing the first few details (title, start date, end date) of the first event over and over until the page times out. At the bottom of the page, the following error then appears:

: Maximum execution time of 30 seconds exceeded in on line

Fatal error/home/website/public_html/wp-content/plugins/gravityview/includes/plugin-and-theme-hooks/class-gravityview-plugin-hooks-all-in-one-seo.php68

I have attached a screenshot as I have turned off WP_DEBUG while I'm waiting for a reply.

The website is using PHP 8.1.
```

Upon further investigation, the issue came from placing the `[gravityview]` shortcode inside an WYSIWYG block of ACF:

![image](https://user-images.githubusercontent.com/1222472/217332655-919922ff-2526-4399-85a4-22d227b5cdb4.png)

![image](https://user-images.githubusercontent.com/1222472/217332527-4d2dcabb-5fd6-4666-a1fd-1ae03aa1a150.png)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2146349219/46779

**Comment by rafaehlers** [comment]
On my tests, no time-out happened, but the `[gravityview]` shortcode simply wasn't executed.

**Comment by rafaehlers** [comment]
Same issue here with `[gventry]`: https://secure.helpscout.net/conversation/2217265380/48386/

**Comment by zackkatz** [comment]
@rafaehlers Please recreate on `try.`

**Comment by zackkatz** [comment]
@rafaehlers Does this work when removing the quotes from the shortcode? `[gravityview id=402]`

**Comment by zackkatz** [comment]
@rafaehlers Please recreate on a `try.` site

**Comment by rafaehlers** [comment]
@zackkatz, it doesn't work when removing the quotes. Sorry, I checked and forgot to reply here. 

Regarding reproducing on `try`, are you going to tackle it soon? I'm trying to avoid filling up `try` with several idle websites.

**Comment by floatytheastronaut** [comment]
FreeScout #76682. <br>https://support.gravitykit.com/conversation/76682?folder_id=1

**Comment by floatytheastronaut** [comment]
FreeScout #77276. <br>https://support.gravitykit.com/conversation/77276?folder_id=1

**Comment by zackkatz** [comment]
@doekenorg Could you please spend an hour or two on this and see if you can spot what's going on?

**Comment by rafaehlers** [comment]
Users notified ✅

**Comment by rafaehlers** [comment]
Note for future Rafa: Widgets work and ACF must be called in the theme template:

```
<?php if ( get_field('name_of_field' ) ): ?>
<?php echo get_field('name_of_field'); ?>
<?php endif; ?>
```
