### ISSUE TITLE
Trigger notification when entry is deleted

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1819]
We need a new event: `GravityView - Entry is deleted`

![image](https://user-images.githubusercontent.com/1222472/219506363-dc2a8eb6-47c0-4ab9-b92f-339a6c7a1f68.png)

Related: https://github.com/gravityview/GravityRevisions/issues/23

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/781782358/19227/

**Comment by zackkatz** [comment]
@rafaehlers Would this be limited to only when GravityView deletes the entry or when Gravity Forms deletes an entry?

**Comment by rafaehlers** [comment]
@zackkatz would be cool to have Gravity Forms support as well since they don't have that built-in.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2221851244/48507

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2242490638/49003
