### ISSUE TITLE
Chained Selects on Search Bar doesn't work anymore

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1824]
Support for Chained Selects on the Search Bar was introduced in [2.14.4](https://github.com/gravityview/GravityView/releases/tag/v2.14.4), but it's not working anymore (2.17.1) with a JS console error:

`Uncaught ReferenceError: GFChainedSelects is not defined`

![image](https://user-images.githubusercontent.com/1222472/221263170-471f2006-4014-4da6-849c-41a3fc12e6b8.png)

I can't see any related Chained Select JS being loaded on the page.

Re: https://github.com/gravityview/GravityView/pull/1701 and https://debug.gravityview.co/view/chained-selects/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2165407625/47253/

**Comment by zackkatz** [comment]
I can no longer reproduce with 2.17.6. Can you confirm @rafaehlers?

**Comment by rafaehlers** [comment]
I confirm it's working again on 2.17.5.
