### ISSUE TITLE
[gvlogic if="context" is="multiple"] doesn't work outside of the View CPT

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1825]
Adding this to a Custom Content widget won't work outside the View custom post type `/view/`.

![image](https://user-images.githubusercontent.com/1222472/221728834-7e16cf27-0c4b-43aa-ae21-6660fc7408cc.png)

![image](https://user-images.githubusercontent.com/1222472/221728891-e7a9a96e-5f2d-4811-aa92-6b28055ffaaa.png)

![image](https://user-images.githubusercontent.com/1222472/221728955-032fe4ea-d131-44c2-a948-aee96bd7b296.png)

Tested on GV 2.17.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2166526401/47277

**Comment by zackkatz** [comment]
It's "Very Low" importance, but it shows that other API stuff may not be working as expected. This should be investigated; I've bumped to "Medium".
