### ISSUE TITLE
get_data_source_header() method calls GFCommon::gf_vars() generating multiple PHP warnings

### ISSUE THREAD

**Issue by 6th-avenue** [GravityKit/GravityView#1828]
Hi!

While investigating an issue on our server, I stumbled on what could be a copy/paste gone wrong issue.

Basically the errors (warnings) I get is for calling GFCommon::gf_vars( $echo = FALSE ) on a non-existing form.

I tracked the issue down to a difference between version 2.15 and 2.16 in class-gravityview-admin-metaboxes.php.

Version 2.16 got a chunk of code inserted, starting from line 230 (version 2.17.1), note the double semi-colons
**$output = $links;;**

I was wondering if this is by design.

Thanks,
Ruud

--------

### Additional information

From version 2.16 onwards when editing a post (WooCommerce product)

**Comment by zackkatz** [comment]
Thanks for reporting, @6th-avenue!

**Comment by zackkatz** [comment]
@6th-avenue this was resolved in [2.17.2](https://github.com/GravityKit/GravityView/releases/tag/v2.17.2). Thank you again for reporting.

**Comment by 6th-avenue** [comment]
👍

**Comment by zackkatz** [comment]
Fixed in fbc72730f
