### ISSUE TITLE
get_data_source_header() method calls GFCommon::gf_vars() generating multiple PHP warnings (2)

### ISSUE THREAD

**Issue by 6th-avenue** [GravityKit/GravityView#1844]
Hi @zackkatz, thanks for looking into this (see #1828).

The fix you applied (removing the extra semicolon) is not actually what I wanted to point out, it is/might/could (probably) be a side-effect of something else what was changed at this point in the file.

between version 2.15 and 2.16, 15 lines of code have been added to the get_data_source_header() method.

Inside the new code a call is made to GFCommon::gf_vars (false) on a non existing form.
This very call throws a bunch of PHP Warnings due to the fact that the form does not exist.

My question is, was it intended to add this piece of code to this method?
And second, when intended, could you perhaps look into a way in which the GFCommon::gf_vars (false) does not throw these warning?

Thanks!

ps: I could not re-open the other bug-report (#1828), so I opened a new one instead

**Comment by zackkatz** [comment]
@6th-avenue This was intentional and it's necessary to render some scripts. We'll handle the notices, thanks for reporting (again) :-) We'll get this fixed.

**Comment by 6th-avenue** [comment]
Hi @zackkatz! 
Thank you for adding the code to not trigger the PHP Warnings getting generated. I feel relived knowing this will save many lines being written into error logs on many servers worldwide. This in turn helps me trying to live a live with the environment in mind where possible.

All the best,
Ruud
