### ISSUE TITLE
Edit and Delete links don't work on Single Entry page when `{user}`  used in `[gravityview]`

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1864]
These two fields don't show up on the Single Entry page if the View is called by a shortcode and filtered using a merge tag:

`[gravityview id='66' search_field="created_by" search_value="{user:ID}"]`

![image](https://github.com/GravityKit/GravityView/assets/1222472/69d5512a-1c6c-4328-b561-74f70211fc48)

Video: https://www.loom.com/share/f5e12dba5e9647b3af09be66173e96c0

A bug similar to these two:

- https://github.com/GravityKit/GravityView/issues/1725
- https://github.com/GravityKit/GravityView/issues/1537

How to reproduce:

- Create a new page and put that shortcode above on it
- Associate one of the entries of that form to a different user than the admin
- Access that page while logged in as this different user
- Check the Single Entry page of that View

Expected: The Link to Edit and Delete Entry fields/links are showing up in the Single Entry page.

Happening on GV 2.17.8

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2278225867/49910/

**Comment by mrcasual** [comment]
Discussion: https://gravitykit.slack.com/archives/CDSTQ9QQ0/p1687267103702869

https://github.com/GravityKit/GravityView/commit/c624cd5d45f4040575c72a1baaeed38e96c6fd42 seems to have fixed it.
