### ISSUE TITLE
Incorrect display of the number field value configured to use a comma as a decimal separator

### ISSUE THREAD

**Issue by mrcasual** [GravityKit/GravityView#1872]
### GF

<img width="986" src="https://github.com/GravityKit/GravityView/assets/2430296/18d3d1f1-26c0-416a-a86f-ce9a3283b545">

---

<img width="270" src="https://github.com/GravityKit/GravityView/assets/2430296/183bc984-3a57-48c7-9da1-d16e291e6fbf">

### GV

<img width="254" src="https://github.com/GravityKit/GravityView/assets/2430296/8b99e367-d2b1-4948-a8e8-839cc837aa74">

**Comment by zackkatz** [comment]
@mrcasual Please review when you have time
