### ISSUE TITLE
Add filter to entry moderation merge tag return url

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1874]
As asked by a user:

>Does GravityView have a filter to set the URL visitors are redirected to after clicking on a public approval link?

I checked the code and there's nothing, perhaps we should add a filter here: https://github.com/GravityKit/GravityView/blob/develop/includes/class-gravityview-entry-approval-merge-tags.php#L662

Related: 
- https://docs.gravitykit.com/article/904-entry-moderation-merge-tags
- https://community.gravityforms.com/t/gravityview-approval-redirect-filter/15500

**Comment by karlemilnikka** [comment]
Thanks for adding the feature request. The suggested filter location is exactly where I added my hard-coded snippet in the meanwhile.

**Comment by davouid** [comment]
Hello, any news on that? 
It would be nice to be able to choose the path or have only the token as merge tag

**Comment by zackkatz** [comment]
This will be included in the next release! The filter's name is `gk/gravityview/approve_link/return_url`. You can see it here: https://github.com/GravityKit/GravityView/commit/ddaab5c66
