### ISSUE TITLE
Swap out the old getting started video for the new one on the "Getting Started" screen

### ISSUE THREAD

**Issue by crbdev** [GravityKit/GravityView#1880]
**Describe the solution you'd like**
If you navigate to "GravityKit" > "Getting Started", you will see the old Getting Started video embedded there. We should update this to the updated video, or preferably embed the Getting Started playlist, which begins with this new video.

Link to playlist --> https://www.youtube.com/playlist?list=PLuSpaefk_eAP_OXQVWQVtX0fQ17J8cn09

![CleanShot 2023-07-27 at 15 55 27@2x](https://github.com/GravityKit/GravityView/assets/50334390/db4b623d-f2fc-4aa3-9724-0788a3f250a4)

**Comment by zackkatz** [comment]
Done!
