### ISSUE TITLE
GravityView 2.18.4/5 prevents the WordPress dashboard dropdown menus from showing up

### ISSUE THREAD

**Issue by bennemann** [GravityKit/GravityView#1899]
The dropdown menu for Tools/Settings/Appearance/...  won't appear when the user is on any Foundation screen (including GravityMigrate).

I was able to reproduce the issue on multiple installs using both Chrome and Firefox. There are no errors in the console.

Toggling the No-Conflict mode doesn't affect this behavior.

GravityView 2.18.3 doesn't present this issue.

**Comment by zackkatz** [comment]
FreeScout #71671. <br>https://support.gravitykit.com/conversation/71671?folder_id=1

**Comment by zackkatz** [comment]
@mrcasual is this already fixed?

**Comment by mrcasual** [comment]
@zackkatz, yes, this was a Foundation issue. Fixed in 2.18.6.
