### ISSUE TITLE
Embed Gravity Forms form as a field

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#1902]
Make it possible to embed a GF form as a field inside a View.

Started with f978c3c81

- [x] When submitting a form, the form submission confirmation appears for every row.
- [x] Add docBlocks
- [x] Testing prepopulating fields (including with quotes and brackets)
- [x] Saving the selected form isn't working
- [x] When submitting a form, automatically add entry meta that says which entry the form was embedded inside. This will allow for easier View creation that only shows associated entries. @mrcasual How should we do this :-)

**Comment by malayladu** [comment]
@zackkatz  

> When submitting a form, the form submission confirmation appears for every row.

For this, I have checked the behaviour of Gravity Forms. If we are adding same form multiple times on the same page, Gravity Form display confirmation message for each form after submitting the form. 

As form is submitting at the Gravity Forms level and confirmation message is also being displayed by the Gravity Forms. So, I believe this needs to be fixed at the Gravity Forms level. Am I missing anything here?

**Comment by mrcasual** [comment]
@malayladu, are we able to track the confirmation message while rendering field output and prevent it from being displayed more than once?

**Comment by malayladu** [comment]
@mrcasual No. We are not able to track it.

**Comment by mrcasual** [comment]
@malayladu, just to make sure, when GV renders an entry, we don't know if the form was submitted and can't control what's displayed as the GF field output?

**Comment by malayladu** [comment]
> @malayladu, just to make sure, when GV renders an entry, we don't know if the form was submitted and can't control what's displayed as the GF field output?

@mrcasual  Can you please explain it a bit further?

**Another thought**

After further debugging, I found that GF adds `form_id` to fields. As form_id for all forms are same on the page and that's why it shows confirmation message on each row.

If we change the `form_id` with some random id, it may solves this issue but we may need to be caution while doing this if someone is using the form id.

**Comment by malayladu** [comment]
@mrcasual Something like this would be helpful.

https://github.com/tyxla/Gravity-Forms-Multiple-Form-Instances/blob/master/gravityforms-multiple-form-instances.php

**Comment by malayladu** [comment]
@zackkatz I have tested populating the fields with quotes and brackets and it seems working.

![field-values-with-brackets-quotes](https://github.com/GravityKit/GravityView/assets/708174/291415dc-9e9c-465f-9288-bfd7368d7d3d)

**Comment by malayladu** [comment]
> * [ ]  Add docBlocks

@mrcasual What's the context of adding DocBlocks here? Where to add the docBlocks?

**Comment by mrcasual** [comment]
> > * [ ]   Add docBlocks
> 
> @mrcasual What's the context of adding DocBlocks here? Where to add the docBlocks?

@malayladu, please check https://github.com/GravityKit/GravityView/commit/f978c3c81cf62b0086cf2d86e9adfa4829ab342c and you'll see that the code isn't documented.
