### ISSUE TITLE
"No rating" is considered a 1 star rating on a Survey field (set up as Rating)

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1906]
It should appear as if no star was given.

## Form editor: 
![image](https://github.com/GravityKit/GravityView/assets/1222472/69cb188a-f920-4fd7-908a-178d92e5663a)

## Entries page:
![image](https://github.com/GravityKit/GravityView/assets/1222472/4717fa40-04b7-4ed1-bcad-61061added5e)

## View editor:
![image](https://github.com/GravityKit/GravityView/assets/1222472/ba00b6ec-d1de-44e7-835a-6cc4b00020d8)

## View output:
![image](https://github.com/GravityKit/GravityView/assets/1222472/858de843-36c8-4d55-b503-c3ee5b5ee12d)

## Desired output:
![image](https://github.com/GravityKit/GravityView/assets/1222472/f2ab8647-04b1-4af6-8623-8ffb77bca14b)

Tested on GV 2.18.6 and Survey add-on 3.8

**Comment by zackkatz** [comment]
FreeScout #72107. <br>https://support.gravitykit.com/conversation/72107?folder_id=1
