### ISSUE TITLE
Conflict with GP Post Content Merge Tags

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1907]
https://gravitywiz.com/documentation/gravity-forms-post-content-merge-tags/

The Merge Tag picker in the block editor toolbar is missing. It used to work with GV 2.15

![image](https://github.com/GravityKit/GravityView/assets/1222472/c5cfdaa3-b8f3-4d29-b1b9-b5c457f333d5)

![image](https://github.com/GravityKit/GravityView/assets/1222472/356bb00a-ad1e-4656-bf29-e15595fa6eab)

Slack discussion with Gravity Wiz: https://gravitykit.slack.com/archives/C023MAWL1JM/p1695154387385019
FS ticket: https://support.gravitykit.com/conversation/72148

**Comment by zackkatz** [comment]
FreeScout #72148. <br>https://support.gravitykit.com/conversation/72148?folder_id=1

**Comment by zackkatz** [comment]
@mrcasual Could you please review and see if it's possible to fix this?

**Comment by mrcasual** [comment]
@zackkatz, I did review and [told Clay about the issue](https://gravitykit.slack.com/archives/C023MAWL1JM/p1695680586217279). This is a tricky one and I think you and I need to discuss the best way to handle it.

**Comment by rafaehlers** [comment]
I retested this with GV 2.29, and GP Post Content Merge Tags version 1.3.15 and that GFs icon doesn't show up anymore, even when deactivating GravityView.

![image](https://github.com/user-attachments/assets/43f0bb05-30a9-4056-be95-0d67b9d98297)
