### ISSUE TITLE
Support relative dates in `[gvlogic]`

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#1909]
It’s silly that relative dates work in advance, filtering and in field conditional logic, but not in gvlogic.

**Comment by rafaehlers** [comment]
@zackkatz we have this now: https://github.com/GravityKit/GravityView/issues/1978 can we close this ticket?

**Comment by zackkatz** [comment]
Yep @rafaehlers, closing.

**Comment by rafaehlers** [comment]
@bennemann why not use/suggest [Field Conditional Logic](https://docs.gravitykit.com/article/753-field-conditional-logic)?
