### ISSUE TITLE
Allow customizing the slug inside the View Settings

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1912]
## Add global settings:

- [x] CPT slug
- [x] Entry endpoint

## Add per-View setting:

- [x] Entry Slug

- Include a message telling users to add unique ID to avoid collisions.

-----

At this moment, the only way to achieve that is by using some code snippets. Not user friendly, at all.

Examples:

- https://docs.gravitykit.com/article/62-changing-the-view-slug
- https://docs.gravitykit.com/article/659-reserved-urls
- https://docs.gravitykit.com/article/57-customizing-urls

We need an interface for this @distich

- These values need to be unique. By default, there should be an `{entry_id}` merge tag. When that's not in the URL, show a notice/warning.

**Comment by distich** [comment]
@zackkatz @rafaehlers 

Concept for this.

![Image](https://github.com/GravityKit/GravityView/assets/4994950/be5c3c4b-fa47-465a-8fdf-c5fc58524355)

**Comment by rafaehlers** [comment]
I liked it!

**Comment by zackkatz** [comment]
https://www.figma.com/file/OM63Lq6eIlzu3nFPR4Xro8/GravityKit-UI%2FUX?type=design&node-id=2061-251&mode=design

**Comment by zackkatz** [comment]
@doekenorg Please work on this next.

**Comment by rafaehlers** [comment]
Implemented on GV 2.29
