### ISSUE TITLE
Add setting for "Only show entries from the currently logged-in user"

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1915]
Add a new setting to the View Settings to make [this process easier](https://docs.gravitykit.com/article/203-how-to-show-only-results-submitted-by-the-current-user) for the user.

How will this integrate with Advanced Filtering?

Ehlers: What if it's a link to auto-configure this setting using Advanced Filtering? When clicking the link, it would auto-configure the necessary filters.

**Comment by zackkatz** [comment]
Closing in favor of https://github.com/GravityKit/Advanced-Filter/issues/150
