### ISSUE TITLE
Likert fields (from the GF Survey Add-On) aren't displayed correctly in Views

### ISSUE THREAD

**Issue by crbdev** [GravityKit/GravityView#1927]
The way likert fields are displayed on the front end is broken in GravityView.
See here for a live demo: https://tful-trout-lebe.try.gravitykit.com/survey-responses/entry/2544/ 

This is how they look when displayed using GV:
![CleanShot 2023-10-10 at 15 52 22@2x](https://github.com/GravityKit/GravityView/assets/50334390/cf49126f-732d-4019-972f-5dd691e526e4)

This is the GF default formatting (how they should look):
![CleanShot 2023-10-10 at 16 00 19@2x](https://github.com/GravityKit/GravityView/assets/50334390/3cef8b28-7feb-4b77-93cd-203873e8d8ec)

--------

**Comment by rafaehlers** [comment]
It's the same issue here: https://github.com/GravityKit/GravityView/issues/1839

**Comment by mrcasual** [comment]
> It's the same issue here: https://github.com/GravityKit/GravityView/issues/1839

#1839 is a different problem and was fixed. This particular issue is about nested table formatting.

**Comment by zackkatz** [comment]
Fixed in 2.19 via b3b92d33b and 88a3ae387
