### ISSUE TITLE
View Settings: Tab contents displaying outside the container

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1934]
I noticed this on the Custom Code tab, Maps, and Single Entry PDF.

![image](https://github.com/GravityKit/GravityView/assets/1222472/721a0327-9e0a-4415-89c3-3e9dec623a3c)

![image](https://github.com/GravityKit/GravityView/assets/1222472/d0e3238c-8a51-4a6a-85f1-61fd3c4ca8ad)

![image](https://github.com/GravityKit/GravityView/assets/1222472/2eb49cd8-5f3b-45e7-a927-7fb6467d8a00)

**Comment by zackkatz** [comment]
Vlad fixed this in 14a7f197f
