### ISSUE TITLE
Merge Tag picker doesn't work on GV 2.19

### ISSUE THREAD

**Issue by bennemann** [GravityKit/GravityView#1935]
The Merge Tag picker for Custom Content fields isn't working on the View editor.

Nothing happens when clicking a field name, and there are no console errors.

![image](https://github.com/GravityKit/GravityView/assets/5726194/89a45d10-119a-4e84-9a7b-3045564ed309)

This issue is specific to GV 2.19 and it can reproduced in any View.

**Comment by floatytheastronaut** [comment]
FreeScout #72997. <br>https://support.gravitykit.com/conversation/72997?folder_id=1
