### ISSUE TITLE
Deprecated notice inside the Page menu on PHP 8.1.23

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1943]
I'm getting this Deprecated notice only when accessing the Pages menu: `/wp-admin/edit.php?post_type=page`

In PHP 8.0.x there's no notice. Seems to be related to PHP 8.1.x

>Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in C:\Users\rafae\Local Sites\gravitykit\app\public\wp-content\plugins\gravityview\includes\class-admin.php on line 212

Tested on GV 2.19.3 and PHP 8.1.23

**Comment by mrcasual** [comment]
Fixed in 2b1291c4f4ce6d05f3e302a528129b18e6dfcfb9.
