### ISSUE TITLE
Edit Entry page: Missing data-label attribute on empty list fields when conditional logic is present

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1957]
The data-label attribute is missing on the Edit Entry page on empty list fields when fields with conditional logic are present.

![missing-data-label](https://github.com/GravityKit/GravityView/assets/1222472/be2e1eac-e857-451a-8cd4-a89f9bca02f8)

Form/Entries/Views: [gk-migrate-gravitykit.local-2023-11-30-1701380210.zip](https://github.com/GravityKit/GravityView/files/13517927/gk-migrate-gravitykit.local-2023-11-30-1701380210.zip)

Tested on GV 2.19.4 and GF 2.7.17

**Comment by floatytheastronaut** [comment]
FreeScout #75300. <br>https://support.gravitykit.com/conversation/75300?folder_id=1

**Comment by zackkatz** [comment]
Closed; see conversation here, which contains a fix using a filter: https://gravitykit.slack.com/archives/C727B06MB/p1701992129756349
