### ISSUE TITLE
Add ability to only show first letter of name fields

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#1965]
Often, you may want to show someone's name as `{First Name} {First Letter}.`; "Janice M." for example.

## To implement:

- [x] Add a checkbox setting for the Name field "Only show initials"
- [x] Add a checkbox setting "Only show initial" for Name sub-input fields:
  - [x] First name
  - [x] Middle name
  - [x] Last name
- [x] Add a filter `gk/gravityview/fields/name/initials` to allow overriding the configuration

Here's what Claude AI says:

```
Initials are used in various ways across different languages and cultures. Here's a brief overview:

English:


Typically use the first letter of the first name and last name (e.g., J.K. Rowling)
Middle initials are sometimes included (e.g., John F. Kennedy)


Chinese:


Usually use the first letter of the surname followed by the first letter(s) of the given name(s)
Example: Wang Xiaoming might be W.X. or W.X.M.


Russian:


Often use three initials: first name, patronymic (father's name), and surname
Example: Alexander Sergeyevich Pushkin might be A.S.P.


Japanese:


Initials are not commonly used in Japanese culture
When used (mostly in international contexts), they follow the Western style


Arabic:


Initials are not traditionally used
In modern contexts, they may follow the Western style when needed


Spanish:


May include initials for both surnames (paternal and maternal)
Example: Gabriel García Márquez might be G.G.M.


Korean:


Initials are not traditionally used
In international contexts, they may use the first letter of the surname followed by given name initials


French:


Similar to English usage, but may include more middle initials
Example: Jean-Paul Charles Aymard Sartre might be J.-P.C.A.S.

These practices can vary depending on personal preference, formal vs. informal contexts, and specific regional or cultural norms. Would you like me to elaborate on any particular language or aspect of initial usage?
```

**Comment by omarkasem** [comment]
@zackkatz 
We can achieve it all except the English ones like (e.g., J.K. Rowling)  (e.g., John F. Kennedy)
For that we might want to add merge tags modifier so they would be on the same line in view table.
Let me know what you think.

![screenshot-gv local-2024 09 14-14_10_33 (1)](https://github.com/user-attachments/assets/52aa0331-9131-4213-a8cc-1f23ef9f85e5)

**Comment by zackkatz** [comment]
@omarkasem That looks good enough for now! We can adjust as-needed in the future.

**Comment by rafaehlers** [comment]
@zackkatz we should have included a merge tag modifier for name fields as well. What do you think?

**Comment by zackkatz** [comment]
@rafaehlers That's a good idea!
