### ISSUE TITLE
Add Entry Lightbox functionality

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#197]
I hadn't planned on supporting this from the Directory add-on, but now three or four customers have shared that they want it.
- Browse entries by Lightbox
- Be able to edit in the lightbox
- Next / Prev buttons for lightbox browsing

Questions:

- How do we handle updating data? When closing the lightbox, if an entry has been edited, outdated values may be shown.
- Will Inline Edit work inside this? 🤯 
- If enabled, should we disable Inline Edit?
- Styling: Do we output styles and the theme headers? Do we display on a blank background? Is there a global setting for this?

Tags:

Open single entry modal pop-up popup pop up

**Comment by soulseekah** [comment]
Wow, this is old!

I am almost sure that this can be accomplished with the `[gventry]` shortcode in some way. Maybe tack on an AJAX handler that does a lightbow with a request to an endpoint that will just do `do_shortcode()` for example. And since the shortcode now supports edit mode (thanks #850). I'll add a small demo to test shortly.

**Comment by soulseekah** [comment]
Here's an mu-plugin that can be used to play with this idea. It's very raw. Edit may not work correctly as there is a lot of context issues especially when POSTing data from within the lightbox. The edit should be AJAXified. Next and Prev not implemented yet. But let's see how it goes.

```php
<?php
/**
 * Experimental lightbox single and edit entry support.
 * As a plugin. The WordPress way.
 * Dirty.
 * Sexy.
 */

/**
 * Output some script scaffolding inline.
 * Kittens dead.
 */
add_action( 'wp_footer', function() {
	?>
		<!-- Uses Featherlight for demo and simplicity purposes. -->
		<link href="//cdn.rawgit.com/noelboss/featherlight/master/release/featherlight.min.css" type="text/css" rel="stylesheet" />
		<script src="//cdn.rawgit.com/noelboss/featherlight/master/release/featherlight.min.js" type="text/javascript" charset="utf-8"></script>

		<script>
			// ID
			jQuery( "[class^='gv-field-']" ).filter( "[class$='-id']" ).find( 'a' ).on( 'click', function() {
				jQuery.get( <?php echo json_encode( admin_url( 'admin-ajax.php' ) ); ?>, {
					'action': 'lightbox_entry_197',
					'id': jQuery( this ).text(), // @todo have id and view_id as data attributes
					'view_id': jQuery( this ).parents( '.gv-container' ).attr( 'class' ).match( /gv-container-(\d+)/ )[1],
				} ).success( function( data ) {
					jQuery.featherlight( jQuery( '<div>' ).html( data ), {
					} );
				} );
				return false;
			} );

			// Edit
			jQuery( "[class^='gv-field-']" ).filter( "[class$='-edit_link']" ).find( 'a' ).on( 'click', function() {
				jQuery.get( <?php echo json_encode( admin_url( 'admin-ajax.php' ) ); ?>, {
					'action': 'lightbox_entry_197',
					'id': jQuery( this ).attr( 'href' ).match( /entry\/(\d+)\// )[1],
					'view_id': jQuery( this ).parents( '.gv-container' ).attr( 'class' ).match( /gv-container-(\d+)/ )[1],
					'edit': true,
				} ).success( function( data ) {
					jQuery.featherlight( jQuery( '<div>' ).html( data ), {
					} );
				} );
				return false;
			} );

		</script>
	<?php
} );

add_action( 'wp_ajax_nopriv_lightbox_entry_197', $callback = function() {
	$id = \GV\Utils::_GET( 'id' );
	$view_id = \GV\Utils::_GET( 'view_id' );

	if ( \GV\Utils::_GET( 'edit' ) ) {
		echo do_shortcode( sprintf( '[gventry id="%d" view_id="%d" edit="true"]', $id, $view_id ) );
	} else {
		echo do_shortcode( sprintf( '[gventry id="%d" view_id="%d"]', $id, $view_id ) );
	}

	exit;
} );
add_action( 'wp_ajax_lightbox_entry_197', $callback );
```

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1474219505/33637/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1577968935/35887?folderId=408730

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1692009083/37978/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1872971177/41097

**Comment by Deepprakashgoyal** [comment]
> Here's an mu-plugin that can be used to play with this idea. It's very raw. Edit may not work correctly as there is a lot of context issues especially when POSTing data from within the lightbox. The edit should be AJAXified. Next and Prev not implemented yet. But let's see how it goes.
> 
> ```
> <?php
> /**
>  * Experimental lightbox single and edit entry support.
>  * As a plugin. The WordPress way.
>  * Dirty.
>  * Sexy.
>  */
> 
> /**
>  * Output some script scaffolding inline.
>  * Kittens dead.
>  */
> add_action( 'wp_footer', function() {
> 	?>
> 		
> 		<link href="//cdn.rawgit.com/noelboss/featherlight/master/release/featherlight.min.css" type="text/css" rel="stylesheet" />
> 		<script src="//cdn.rawgit.com/noelboss/featherlight/master/release/featherlight.min.js" type="text/javascript" charset="utf-8"></script>
> 
> 		<script>
> 			// ID
> 			jQuery( "[class^='gv-field-']" ).filter( "[class$='-id']" ).find( 'a' ).on( 'click', function() {
> 				jQuery.get( <?php echo json_encode( admin_url( 'admin-ajax.php' ) ); ?>, {
> 					'action': 'lightbox_entry_197',
> 					'id': jQuery( this ).text(), // @todo have id and view_id as data attributes
> 					'view_id': jQuery( this ).parents( '.gv-container' ).attr( 'class' ).match( /gv-container-(\d+)/ )[1],
> 				} ).success( function( data ) {
> 					jQuery.featherlight( jQuery( '<div>' ).html( data ), {
> 					} );
> 				} );
> 				return false;
> 			} );
> 
> 			// Edit
> 			jQuery( "[class^='gv-field-']" ).filter( "[class$='-edit_link']" ).find( 'a' ).on( 'click', function() {
> 				jQuery.get( <?php echo json_encode( admin_url( 'admin-ajax.php' ) ); ?>, {
> 					'action': 'lightbox_entry_197',
> 					'id': jQuery( this ).attr( 'href' ).match( /entry\/(\d+)\// )[1],
> 					'view_id': jQuery( this ).parents( '.gv-container' ).attr( 'class' ).match( /gv-container-(\d+)/ )[1],
> 					'edit': true,
> 				} ).success( function( data ) {
> 					jQuery.featherlight( jQuery( '<div>' ).html( data ), {
> 					} );
> 				} );
> 				return false;
> 			} );
> 
> 		</script>
> 	<?php
> } );
> 
> add_action( 'wp_ajax_nopriv_lightbox_entry_197', $callback = function() {
> 	$id = \GV\Utils::_GET( 'id' );
> 	$view_id = \GV\Utils::_GET( 'view_id' );
> 
> 	if ( \GV\Utils::_GET( 'edit' ) ) {
> 		echo do_shortcode( sprintf( '[gventry id="%d" view_id="%d" edit="true"]', $id, $view_id ) );
> 	} else {
> 		echo do_shortcode( sprintf( '[gventry id="%d" view_id="%d"]', $id, $view_id ) );
> 	}
> 
> 	exit;
> } );
> add_action( 'wp_ajax_lightbox_entry_197', $callback );
> ```

I have tried this, but not working

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/1982963166/43015/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2061777229/44663

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2066889091/44804/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2083209632/45364/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2176471049/47507/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2177536831/47525

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2196037619/47858

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2252596182/49304/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2255400182/49389

**Comment by floatytheastronaut** [comment]
FreeScout #75256. <br>https://support.gravitykit.com/conversation/75256?folder_id=4

**Comment by floatytheastronaut** [comment]
FreeScout #76854. <br>https://support.gravitykit.com/conversation/76854?folder_id=1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2622855275/55180

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2657184499/55977

**Comment by rafaehlers** [comment]
```
We have custom pages on our website that allows shows the submitted entry data once an application has been accepted. We have enhanced these pages this year, to allow users to edit their submitted information on that page. I have successfully added the gravity view form in edit mode into a modal on the page using the gventry shortcode. The problem though is that when the submit button is pushed the page is refreshed in order to show if there are any errors on the page or if the data was updated.
Example: echo do_shortcode('[gventry entry_id="' . $entryId . '" view_id="688358" edit="1"]');


I am working to submit this update through AJAX instead. Is there an API endpoint or a specific URL that I can submit a gravityview form object to?

```

https://secure.helpscout.net/conversation/2657184499/55977/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2669423770/56300

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2700611025/57194?viewId=408730

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2718705479/57625

**Comment by rafaehlers** [comment]
Customers notified ✅
