### ISSUE TITLE
Out of memory error in wp_debug_backtrace_summary when GP Limit Submissions is in use

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1976]
>I am using GF Limit Submission from Gravity Perks on one of my forms . There is no issue.
>As soon as I activated your Gravity View plugin, my form is not loaded and throws an error below.
>`Allowed memory size of 536870912 bytes exhausted (tried to allocate 2896144 bytes) in /PATH/wp-content/plugins/gravityview/includes/class-gravityview-logging.php on line 59`

https://github.com/GravityKit/GravityView/blob/develop/includes/class-gravityview-logging.php#L59

Also, Vlad says this can be mitigated with:
>debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 10);

Experienced with GV 2.19.5, GP Limit Submissions 1.1.13, and GFs 2.8.2

**Comment by floatytheastronaut** [comment]
FreeScout #76682. <br>https://support.gravitykit.com/conversation/76682?folder_id=1

**Comment by rafaehlers** [comment]
Can't replicate this anymore with GV 2.29 and Limit Submissions 1.1.19.
