### ISSUE TITLE
"Link to Single Entry PDF" field does not appear in the View editor on the Multiple Entries tab

### ISSUE THREAD

**Issue by crbdev** [GravityKit/GravityView#1977]
**Describe the Issue**
After playing around with PDF for GravityView I noticed that the "Link to Single Entry PDF" and "Share Single Entry PDF" fields do not appear in the View editor's field picker when on the Multiple Entries layout. I believe this worked before, as I created a demo with the "Link to Single Entry PDF" field on the Multiple Entries layout. 

Before:
![CleanShot 2024-02-01 at 15 10 48@2x](https://github.com/GravityKit/GravityView/assets/50334390/a9020031-0019-4848-b223-a779922957d9)

Now:
![CleanShot 2024-02-01 at 15 12 14@2x](https://github.com/GravityKit/GravityView/assets/50334390/45775c70-1a46-490d-8a1e-5fa2591303d7)

**Comment by rafaehlers** [comment]
@jakejackson1 do you remember if they were available?

**Comment by jakejackson1** [comment]
@rafaehlers @crbdev only the Link to Single Entry PDF field is available from the Single Entry Layout. The Share PDF field is not. I can confirm in the latest version of GravityView the field isn't showing on the Multi View. Reviewing now.

**Comment by jakejackson1** [comment]
Not sure exactly what changed in GravityView, but the legacy "directory" context no longer worked. I've added the "multiple" context, which seems to have fixed it: https://github.com/GravityPDF/pdf-for-gravityview/pull/32/files

Will publish

**Comment by rafaehlers** [comment]
Thanks @jakejackson1

**Comment by crbdev** [comment]
Awesome. Thanks, @jakejackson1!

**Comment by jakejackson1** [comment]
Resolved https://github.com/GravityPDF/pdf-for-gravityview/releases/tag/1.0.1
