### ISSUE TITLE
"Invalid post type" when Gravity Forms isn't active

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#1979]
**Describe the Issue**

1. Deactivate Gravity Forms and GravityView
2. Activate GravityView
3. Go to All Views

**What happens:**
You see "Invalid post type."

![](https://i.gravitykit.com/i/9KHXtr+)

**What should happen:**
You see a message about GravityView requiring Gravity Forms.

**Comment by rafaehlers** [comment]
This has been fixed! It's not possible anymore to activate GravityView without activating Gravity Forms as well.

![image](https://github.com/user-attachments/assets/cbb5ad3e-c493-4f1d-bf57-be9d440644bf)
