### ISSUE TITLE
PHP 8.2: Single Entry View gives 404

### ISSUE THREAD

**Issue by tobifjellner** [GravityKit/GravityView#1985]
**Describe the Issue**
Use PHP 8.2
When you try to view a Single Entry on the front, you get a 404

--------

### Additional information

**This issue happens in the following settings:**

_Please try to re-create the issue in each rendering mode. This helps debug the problem._

- [ ] View
- [ ] Embedded via shortcode
- [ ] Embedded via oEmbed

**If shortcode, paste the shortcode below**

`[replace me]`

**Are Advanced Filter filters configured for the View?**

- [ ] Yes
- [ ] No

**If yes, please drag a screenshot below:**

**Comment by floatytheastronaut** [comment]
FreeScout #77235. <br>https://support.gravitykit.com/conversation/77235?folder_id=1

**Comment by tobifjellner** [comment]
Double- checked on a minimal install. There it works.
