### ISSUE TITLE
Add support for `:human` merge tag modifiers on all Date fields

### ISSUE THREAD

**Issue by tobifjellner** [GravityKit/GravityView#1990]
A customer has suggested that we should add possibility to show timestamps as relative time/relative date

i.e. "Yesterday", "2 hours ago", "Tomorrow", etc.

By UI setting and/or field code parameter.

https://developer.wordpress.org/reference/functions/human_time_diff/ should make this relatively easy.

The tricky part would of course be that only timestamps are truly date and time in one in Gravity Forms.

**Comment by floatytheastronaut** [comment]
FreeScout #77495. <br>https://support.gravitykit.com/conversation/77495?folder_id=4

**Comment by zackkatz** [comment]
@rafaehlers Please test to see if `:human` works with all date fields, not just `{date_created}` and `{date_updated}`.

**Comment by rafaehlers** [comment]
It doesn't, unfortunately:

![image](https://github.com/user-attachments/assets/b4bf1bc2-b41a-4d5f-8765-757d0e00d2ed)
