### ISSUE TITLE
PHP 8.2 Deprecation Notices

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1999]
A customer shared:

>Upgraded to PHP 8.2 and now the Shortcode is not working. I recently upgraded my site to PHP 8.2 and now the shortcode is failing. Here is the errors I am getting

>Deprecated Return type of GV\View::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-view.php:836
1 Plugin: gravityview
Deprecated Return type of GV\View::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-view.php:852
1 Plugin: gravityview
Deprecated Return type of GV\View::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-view.php:888
1 Plugin: gravityview
Deprecated Return type of GV\View::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-view.php:900
1 Plugin: gravityview
Deprecated Return type of GV\GF_Form::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-form-gravityforms.php:220
1 Plugin: gravityview
Deprecated Return type of GV\GF_Form::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-form-gravityforms.php:235
1 Plugin: gravityview
Deprecated Return type of GV\GF_Form::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-form-gravityforms.php:248
1 Plugin: gravityview
Deprecated Return type of GV\GF_Form::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-form-gravityforms.php:260
1 Plugin: gravityview
Deprecated Return type of GV\GF_Entry::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-entry-gravityforms.php:130
1 Plugin: gravityview
Deprecated Return type of GV\GF_Entry::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-entry-gravityforms.php:145
1 Plugin: gravityview
Deprecated Return type of GV\GF_Entry::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-entry-gravityforms.php:158
1 Plugin: gravityview
Deprecated Return type of GV\GF_Entry::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-entry-gravityforms.php:170
1 Plugin: gravityview
Deprecated Return type of GV\Multi_Entry::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-entry-multi.php:111
1 Plugin: gravityview
Deprecated Return type of GV\Multi_Entry::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-entry-multi.php:126
1 Plugin: gravityview
Deprecated Return type of GV\Multi_Entry::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-entry-multi.php:142
1 Plugin: gravityview
Deprecated Return type of GV\Multi_Entry::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
wp-content/plugins/gravityview/future/includes/class-gv-entry-multi.php:154

**Comment by floatytheastronaut** [comment]
FreeScout #77803. <br>https://support.gravitykit.com/conversation/77803?folder_id=1

**Comment by rafaehlers** [comment]
We can probably close this issue. We've been reporting individual/specific deprecated notices in separate issues: https://github.com/search?q=repo%3AGravityKit%2FGravityView+deprecated&type=issues
