### ISSUE TITLE
JetPack Blocks causing timeout when editing page with View block embedded

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2027]
When trying to edit any page containing a View block this timeout error showed up:
>An error of type E_ERROR was caused in line 214 of the file /home/userxxx/public_html/wp-content/plugins/gravityview/vendor_prefixed/illuminate/support/Arr.php. Error message: Maximum execution time of 40 seconds exceeded

While investigating this issue, [I found a fatal error](https://github.com/GravityKit/Social-Sharing/issues/45), so this is more like a placeholder until we fix the other issue first.

![image](https://github.com/GravityKit/GravityView/assets/1222472/4d78b542-4c40-4bc9-a8fb-ef71fe62ab47)

Happened on PHP 7.4, JetPack 13.3, and GV 2.21.2. Theme Twenty Fourteen

It looks like the JetPack Blocks feature was introduced in version 13.2: https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/CHANGELOG.md#changelog

**Comment by mrcasual** [comment]
Fixed in b086b23cfe74881e3d1527862414a0cc984f94a6. Confirmed working by the customer.
