### ISSUE TITLE
Invalid secret warning for secure Views on LifterLMS student dashboard 

### ISSUE THREAD

**Issue by crbdev** [GravityKit/GravityView#2028]
After enabling the GravityView integration for LifterLMS, any secure Views added to the student dashboard will be replaced by the below warning ("Invalid secret").

![CleanShot 2024-04-15 at 12 31 09@2x](https://github.com/GravityKit/GravityView/assets/50334390/d4a59ed9-293a-4e23-8611-72990e21543d)

--------

**Steps to reproduce:**
1. Install the LifterLMS plugin and complete the setup wizard
2. Go to "LifterLMS" > "Settings" > "Integrations" > "GravityView" and enable the integration
3. Rename the menu label to "My Views", select a **secure** View from the "Show the following Views" selection box, save changes
4. Navigate to the LifterLMS Student Dashboard page
5. Click "My Views"; see warning displayed.

**Comment by zackkatz** [comment]
@crbdev I wasn't able to reproduce this.

Could this be related to cloning Views between sites?

**Comment by crbdev** [comment]
@zackkatz Not sure! I'll test this some more and report back!

**Comment by crbdev** [comment]
@zackkatz I believe you're right! It seems it's an issue with cloning Views using GravityMigrate

**Comment by rafaehlers** [comment]
@crbdev can we close this ticket then?
