### ISSUE TITLE
Prioritise in navigation the Getting Started page

### ISSUE THREAD

**Issue by karmatosed** [GravityKit/GravityView#2037]
**Is your feature request related to a problem? Please describe.**
Starting to use the plugin is one of the hurdles for many, so ensuring that useful pages like 'Getting Started' are easily found helps with onboarding. Currently, this page isn't the first one in the navigation menu for this plugin, this means it often is later to discover for the customer.

**Describe the solution you'd like**
Prioritize the 'Getting Started' page by making it the first page link in navigation. This is shown by solution 'B' in the following screenshot.

![Frame 39](https://github.com/GravityKit/GravityView/assets/253067/a7df6c09-3a86-498f-8aed-f94e896a3e44)

**Considerations**
It may be preferred to have it contained within each plugin group within the navigation still, should multiple pages exist across plugins. It is still my recommendation to have any starting page be the top navigation item even in a sub-group. For example in this case it would read:

- Getting Started
- New View
- All Views

**Comment by zackkatz** [comment]
Closed to be handled here: https://github.com/orgs/GravityKit/projects/35
