### ISSUE TITLE
Time field Merge Tag doesn't support fomatting

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2040]
A customer asked us how to remove the leading zeros in a time field merge tag because he wanted it to follow his WordPress settings:

![image](https://github.com/GravityKit/GravityView/assets/1222472/db7c1ea8-d7ce-4fc6-a46f-185dcf2929a3)

![image](https://github.com/GravityKit/GravityView/assets/1222472/8c9f0dcf-6e44-4bb0-84f5-efc12c25958a)

![image](https://github.com/GravityKit/GravityView/assets/1222472/b1b14861-25c8-4a34-bf06-623857510a5f)

Gravity Forms does not have any modifiers for time fields: https://docs.gravityforms.com/time/#h-modifiers

We and Gravity Forms have plenty of options for formatting date fields: https://docs.gravitykit.com/article/331-date-created-merge-tag but none for time fields.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2584574763/54187

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2673797825/56419/

**Comment by mrcasual** [comment]
This could probably use a KB.

**Comment by rafaehlers** [comment]
Customers notified! ✅
