### ISSUE TITLE
View can't display Arabic filenames for File Upload field

### ISSUE THREAD

**Issue by bennemann** [GravityKit/GravityView#2051]
If I add a File Upload field to a View, it won't display links where the filename is in Arabic:

![image](https://github.com/GravityKit/GravityView/assets/5726194/16040f67-1b5a-474f-82b9-95821935b80b)

Reproduced here:
https://debug.try.gravitykit.com/view/test-file-upload/entry/23265/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2592002958/54383/

**Comment by rafaehlers** [comment]
Customer notified about the filter.
