### ISSUE TITLE
The "Add All Form Fields" option in the Multiple or Single Entry screens adds fields in random order

### ISSUE THREAD

**Issue by bennemann** [GravityKit/GravityView#2052]
![image](https://github.com/GravityKit/GravityView/assets/5726194/b43d1225-1c68-4b04-b763-96640cbf2877)

When someone uses the "Add All Form Fields" option in the Multiple or Single Entry screens, the fields are added to the View in a random order.

To reproduce it, just use the option in any View: 
Separate Ajax requests are triggered for each form field, and they are displayed asynchronously as each request is complete.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2597292716/54493

**Comment by rafaehlers** [comment]
Customer notified!
