### ISSUE TITLE
Add more celebration when create a View for first time

### ISSUE THREAD

**Issue by karmatosed** [GravityKit/GravityView#2057]
**Is your feature request related to a problem? Please describe.**
When you create a View it's pretty exciting - let's celebrate that more! This idea is to iterate the copy a little and bring some sparkles quite literally to Floaty. What this does is also give an opportunity improve the usability of the experience.

<img width="1618" alt="celebrationimage" src="https://github.com/GravityKit/GravityView/assets/253067/e0f662a7-59b5-43b2-a998-270b160389eb">

**Describe the solution you'd like**
The changes initially suggested are copy and image, but they could go further in later explorations. I would suggest exploring if we want such colorful stars or simple single colors. The idea of star confetti seems aligned to Floaty's branding enough to not have deviated too far.

<img width="1452" alt="celebrationimage01" src="https://github.com/GravityKit/GravityView/assets/253067/99af1b5a-c600-4607-928c-f3894057a861">

Whilst this does take up more space, by doing so it forces more attention on the fact you have taken an action, you can celebrate as you should.

There are other minor copy changes so cc'ing in @crbdev as there is a cross-over for some other efforts here. The idea is to improve and easy, lead to documentation perhaps here.

**Describe alternatives you've considered**
One thing to consider might be to re-direct back to another page, next step in journey. However, for now having a celebration here is good to improve.

**Comment by crbdev** [comment]
This is fantastic and I think it's much-needed! But shouldn't this be part of our overall onboarding wizard/flow that we are planning to build out instead of an isolated issue? Or are we starting small?

**Comment by karmatosed** [comment]
The initial idea was to start small @crbdev but I think you have a valid point after syncing with @zackkatz I am going to close this and move to a project to create some fuller flows.
