### ISSUE TITLE
Add new notification event for when an entry has been updated

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2065]
At this moment, this is only available when GravityRevisions is installed, but I believe GravityView should be independent of GravityRevisions for that functionality.

GravityRevisions: https://docs.gravitykit.com/article/485-email-notify-entries-updated-gravity-forms

- [x] Add `GravityRevisions - ` Prefix to the GravityRevisions option
- [x] Add `GravityView - Entry is updated` option
- [x] Copy [functionality from GravityRevisions](https://github.com/GravityKit/GravityRevisions/blob/394d9f1ceb10fc70b9581f1e3e7d7f18b33c87aa/includes/notifications.php#L3)

![image](https://github.com/GravityKit/GravityView/assets/1222472/cc43b8c2-9a45-4b81-a5eb-35a672bc00c0)

**Comment by omarkasem** [comment]
@rafaehlers 
I have already finished point 1 in this PR https://github.com/GravityKit/GravityView/pull/2185

**Comment by rafaehlers** [comment]
@omarkasem I saw that! Thank you!
