### ISSUE TITLE
"Mark as Read" throws an error in Edit Entry mode

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#2070]
> Anytime a client goes to view or a team member goes to edit an entry they receive an error in the attached screenshot below: "There was an error marking this entry as read."

[Slack Message](https://gravitykit.slack.com/archives/C727B06MB/p1717099443730499)

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/2612094941/54878?viewId=408730

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2612738135/54898

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2615809268/54965/

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2616837139/55007

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2616985731/55016

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2629635158/55325/

**Comment by rafaehlers** [comment]
`add_filter('gk/gravityview/field/is-read/print-script', '__return_false');` seems to fix temporarily

**Comment by mrcasual** [comment]
This was fixed in https://github.com/GravityKit/GravityView/releases/tag/v2.25
