### ISSUE TITLE
User Registration Add-on - Allow user activation on the View 

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2076]
- [x] Add User Activation field type to GravityView that shows ONLY WHEN User Activation is set to Manual
- [x] On the front-end, output the output from `GF_Pending_Activations::add_pending_activation_meta_box()`
- [x] Make it an AJAX link so that page refresh isn't needed

@omarkasem When you start working on this, please ask for access to the User Registration Add-On in Slack.

At this moment, it's only possible to manually activate a user from the backend on the form settings.

![image](https://github.com/GravityKit/GravityView/assets/1222472/2ac86fe0-6b6c-49d7-be97-8020060cb479)

The idea is to activate users directly from the View on the front end.

![image](https://github.com/GravityKit/GravityView/assets/1222472/ebedd6d9-4007-4ab4-b7af-43c3485e15a3)

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2620621453/55131

**Comment by zackkatz** [comment]
@crbdev What other things would you want to see here?

**Comment by crbdev** [comment]
@zackkatz I think @rafaehlers covered it 👍
