### ISSUE TITLE
Incompatibility issues with WooCommerce Subscriptions

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2079]
[A customer reported](https://secure.helpscout.net/conversation/2623091686/55187?viewId=408730):

>When woocommerce subscriptions plugin is active... you're unable to access single entry pages in any view. It throws a 404 page not found error. When I deactivate woocommerce subscriptions, it doesn't do that.
>When I downgrade the subscriptions plugin to an older version, it works fine. This is the same issue I'm having with GravityFlow as well. I have already reported the bug to them.

Further debug from Gravity Flow in the ticket: https://secure.helpscout.net/conversation/2623091686/55187?viewId=408730#thread-7894287704

**Comment by omarkasem** [comment]
@mrcasual 
I tried with woo sub Version 6.4.1 and can't reproduce it, i also don't have access to helpscout to view more info about his setup and configuration to try to match is environment

**Comment by mrcasual** [comment]
@rafaehlers, can this be closed?

**Comment by rafaehlers** [comment]
@mrcasual It seems so. I suspect this has been fixed on WooCommerce's end.
