### ISSUE TITLE
Shortcodes inside HTML Block fields are not parsed on the Multiple Entries page

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2081]
...but they do on the Single Entry page or Edit Entry page. Why is that?

![image](https://github.com/GravityKit/GravityView/assets/1222472/625a5c29-64d4-4d58-892a-885c6c9154f3)

![image](https://github.com/GravityKit/GravityView/assets/1222472/078454c0-2b95-4f0c-8dcd-b4a4331a850b)

![image](https://github.com/GravityKit/GravityView/assets/1222472/00d170f8-b3ee-4048-97c3-37a094e455f6)

https://debug.try.gravitykit.com/view/html-field/entry/23290/

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2620700424/55134

**Comment by rafaehlers** [comment]
@omarkasem is it possible for you to prioritize this one?

**Comment by omarkasem** [comment]
@rafaehlers So all regular shortcodes are working fine, it's just the gv_entry_link one wasn't showing up as the logic it had that it will try to get view_id inside the single entry which it did fine but not the multi entries page.

I fixed that now with the PR

**Comment by rafaehlers** [comment]
Awesome! Thanks @omarkasem
