### ISSUE TITLE
`:format` Merge Tag modifier for time fields not considering website UTC

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2102]
When testing the `:format` merge tag modifier for time fields [from this PR](https://github.com/GravityKit/GravityView/pull/2080) I've found this problem:

![image](https://github.com/user-attachments/assets/40c3e15e-4f80-49d7-bccc-673ed5e1efca)

Changing the website timezone to UTC corrected the date:

![image](https://github.com/user-attachments/assets/42701321-de9f-44dd-bc27-f7e634bf6f72)

![image](https://github.com/user-attachments/assets/7c03a4b7-53a6-4ddf-8757-638959aea2e1)

It looks like UTC isn't being considered.

Once this has been implemented, a new doc must be created specifically for this modifier.

**Comment by mrcasual** [comment]
@omarkasem, please work on this.
