### ISSUE TITLE
Fatal error on the Approval Field on the Edit Entry page of a View using Multiple Forms

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2103]
Related to: https://github.com/GravityKit/GravityView/pull/2077

It only happens if there's a field added to the Edit Entry layout:

![image](https://github.com/user-attachments/assets/fd70cc25-2935-459a-99fa-6f86ded10ac1)

To test, go here: https://debug.try.gravitykit.com/view/multiple-forms-form-a-form-b/entry/10040/ and click on Edit Entry.

Introduced in GV 2.26

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2676085977/56478

**Comment by zackkatz** [comment]
@rafaehlers Please notify
