### ISSUE TITLE
Error while trying to install Datatables from 'Add New View' page

### ISSUE THREAD

**Issue by Mwalek** [GravityKit/GravityView#2110]
Error while trying to install Datatables from 'Add New View' page

## Steps to reproduce

1. Open existing View
2. Click "New View" button
3. Give the View a title
4. Select a form to connect to the View
5. Click the install button on Datatables

**Expected:** No error is shown

**Actual**: An error message "Product with '' text domain not found." is shown

--------

### Additional information

This only happens when you first select the View type when creating the View. It works fine if you select a table and then install DataTables from the View type selector under each layout.

**Are Advanced Filter filters configured for the View?**

- [ ] Yes
- [x] No

**Comment by mrcasual** [comment]
@Mwalek, is this still relevant?

**Comment by Mwalek** [comment]
@mrcasual no, this was resolved in https://github.com/GravityKit/GravityView/pull/2112
