### ISSUE TITLE
Moving from date to date range in search widget causes fatal error

### ISSUE THREAD

**Issue by omarkasem** [GravityKit/GravityView#2115]
Moving from date to date range in search widget causes fatal error to recreate it:
- Add a field that has date and date range in search widget like https://github.com/GravityKit/Event-Field/pull/63
- Do a search with a date then go back and change the type to date range
- When you refresh the page with the old search parameters it causes a fatal error

**Comment by mrcasual** [comment]
@omarkasem, we were unable to reproduce the issue using `develop` on GravityView and `issue/53-support-gravityviews-search-bar2` on Event Field. Could you please record a video or reproduce it on https://site.try.gravitykit.com/?

**Comment by rafaehlers** [comment]
I was able to reproduce it:

![image](https://github.com/user-attachments/assets/bf706440-3d98-43c2-b109-d64b4ccf2b13)

**Comment by rafaehlers** [comment]
I was able to reproduce it and the PR fixed it!

**Comment by mrcasual** [comment]
> I was able to reproduce it and the PR fixed it!

@rafaehlers, which WP/PHP/GV versions are you using? Did you follow @omarkasem's steps? Any other suggestions for reproducing this consistently, given that both @Mwalek and I were unsuccessful?

**Comment by rafaehlers** [comment]
@mrcasual I followed Omar's steps precisely as he described it.

**Comment by mrcasual** [comment]
@rafaehlers, OK, since you were able to reproduce it, please come up a changelog entry.

**Comment by rafaehlers** [comment]
@mrcasual 

> Fixed: Fatal Error that happened when a date search is performed against incorrect date fields.

**Comment by mrcasual** [comment]
> incorrect date fields.

@rafaehlers, what does this part mean? What makes a date incorrect? Format?
