### ISSUE TITLE
State Not Updated Across Page Elements After Installation or Activation

### ISSUE THREAD

**Issue by Mwalek** [GravityKit/GravityView#2117]
After performing installation, activation, or purchase actions on any element within the View edit page, such as through the layout dropdown or settings metabox placeholders, the state of all relevant page elements should be updated to reflect the latest changes.

Currently, this state update is not consistently applied across all page elements, leading to discrepancies in the displayed status.

For example, when a layout is installed from the main area of the GUI, the "View type" dropdown does not update to reflect the installation. The dropdown should no longer show an "install" button for the layout that has just been installed, but currently, it does.

**Steps to Reproduce:**

1. Create a new View.
2. Enter a title for the View.
3. Select a form to connect to the View.
4. Choose a View type that is not already installed by clicking the "Install" button from the main area.
5. Perform an installation, activation, or purchase action for a plugin or View type.
6. Check the layout dropdown and the settings metabox placeholders for any inconsistencies.

**Expected Behavior:**

After any installation, activation, or purchase action, all page elements, including the layout dropdown and settings metabox placeholders, should immediately reflect the updated state. For example, the dropdown should no longer show an "install" button for installed View types, and the settings metabox should display the correct status of installed or activated functionalities.

**Actual Behavior:**

The layout dropdown and settings metabox placeholders do not consistently update to reflect the latest state after performing installation, activation, or purchase actions. As a result, the page elements may show outdated information or incorrect statuses.

For example, the "View type" dropdown still shows the "Install" button for the View type that was just installed, even though the installation was successful.

**Additional Info:**

Related to https://github.com/GravityKit/GravityView/issues/2110

**Comment by mrcasual** [comment]
@Mwalek, what about the settings metabox placeholders?

**Comment by Mwalek** [comment]
Thanks! Was not aware about that. Updating the issue ...

**Comment by mrcasual** [comment]
@Mwalek, is this still relevant?

**Comment by Mwalek** [comment]
@mrcasual this was resolved in https://github.com/GravityKit/GravityView/pull/2144
