### ISSUE TITLE
Survey field ratings are incorrect for Views embedded in other Views

### ISSUE THREAD

**Issue by crbdev** [GravityKit/GravityView#2125]
When a View in embedded in another View, star ratings show up as the oppposite of what they should be (i.e., a 5-star rating shows up as a 1-star rating). It appears to work with DataTables. @Mwalek can you see if you can reproduce this?

Loom: https://www.loom.com/share/373dded5c2e247dcbcc8366ddd68168b 

Steps to reproduce:

1. Create a Table View with any data
2. Create a new form that includes a survey field (type: rating)
3. Create another table View to display ratings
4. Embed the rating form and View into the first View's Single Entry layout
5. Submit ratings and refresh the page – confirm ratings are incorrect
6. Change the rating View layout from Table to DataTables and confirm that ratings are now correct
7. Check with other View types

**Comment by Mwalek** [comment]
I can reproduce the issue:

https://www.loom.com/share/e1a3194eab864a50b6bcb36dd09a5951?sid=7097cda3-ac4a-4263-88b7-5e994939a0ea

Changing the rating view type to DataTables makes the ratings show up correctly.

**Comment by mrcasual** [comment]
@Mwalek, please share the GravityMigrate dump or a link to the `try` site.

**Comment by Mwalek** [comment]
@mrcasual the dump is attached:

[gk-migrate-1gk-qa.local-2024-08-27-1724766774.zip](https://github.com/user-attachments/files/16763136/gk-migrate-1gk-qa.local-2024-08-27-1724766774.zip)

**Comment by omarkasem** [comment]
@mrcasual It's fixed now with this PR https://github.com/GravityKit/GravityView/pull/2157
