### ISSUE TITLE
Incorrect Number of Entries Displayed After Editing View in the Same Tab

### ISSUE THREAD

**Issue by Mwalek** [GravityKit/GravityView#2148]
### Steps to Reproduce:
1. Create a View based on any form with existing entries (e.g., 10 entries).
2. Select the "Datatables" layout.
3. (Optional) In "View Settings," ensure "Enable Caching" is unchecked.
4. Navigate to the "Multiple Entries" setting and set the "Number of Entries Per Page" to a value lower than the total number of entries (e.g., 7).
5. Save the View.
6. Visit the front end, *in the same tab*, and confirm that the specified number of entries is displayed per page.
7. Edit the same View, *in the same tab*, and further reduce the "Number of Entries Per Page" (e.g., set it to 4).
8. Revisit the front end.

### Actual Result:
The number of entries per page does not update correctly after editing the View in the same tab.

### Expected Result:
The front end should display the updated number of entries per page as specified in the View settings.

Loom Video: https://www.loom.com/share/f4c18385c55e42559f2e3904cd44c924?sid=71746e54-825b-47ea-9205-7af24fbb248b

**Comment by mrcasual** [comment]
@Mwalek, this should probably be moved to the DataTables (DT) repo. Also, have you tried clearing DT cache? Read [this](https://gravitykit.slack.com/archives/C727B06MB/p1726621081930039) and retest.

**Comment by Mwalek** [comment]
@mrcasual thanks for sharing the filter `gravityview_datatables_js_options`, the problem isn't there when the filter is used.

I'm surprised disabling the cache in the View settings didn't do the trick though.

<img width="713" alt="Screenshot 2024-09-26 at 7 22 04 PM" src="https://github.com/user-attachments/assets/19994b41-9559-4c1c-9716-a38d3e2b421e">

Let me know if I can proceed to create this issue under DT.

**Comment by mrcasual** [comment]
@Mwalek, you already created an issue 3 weeks ago: https://github.com/GravityKit/DataTables/issues/239. #2148 is not a GravityView issue. Closing.

**Comment by Mwalek** [comment]
Got it! Sorry about the duplicate issue, weird that I forgot.
