### ISSUE TITLE
 Wordfence conflict causes fatal error when deleting entries

### ISSUE THREAD

**Issue by bennemann** [GravityKit/GravityView#2165]
When Wordfence is installed, deleting an entry throws the following fatal error:

    Fatal error: Uncaught Error: Too few arguments to function wordfence::wpRedirectFilter(), 
    1 passed in /.../wp-includes/class-wp-hook.php on line 324 
    and exactly 2 expected in /.../wp-content/plugins/wordfence/lib/wordfenceClass.php on line 1460

This issue was introduced in [commit 63a5f11](https://github.com/GravityKit/GravityView/commit/63a5f11e41c782b5fcddba6a7abcbc3331775c0a), where `apply_filters('wp_redirect', $url)` is called with only one argument, while Wordfence expects two.

**Steps to Reproduce**:
1. Activate Wordfence.
2. Delete an entry.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2727896021/57839

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2733631391/58019/

**Comment by rafaehlers** [comment]
Customers were sent the latest build ✅
