### ISSUE TITLE
Warning message appears when adding merge tag to custom entry slug field

### ISSUE THREAD

**Issue by crbdev** [GravityKit/GravityView#2184]
In the Single Entry settings in the View settings, there is an option to add a custom entry slug. There is a merge tag picker indicating it's possile to use merge tags here. However, when adding a merge tag, a warning message appears. I believe the issue here is the colon (':') in the merge tag.

![CleanShot 2024-10-29 at 10 42 06@2x](https://github.com/user-attachments/assets/49aec0cb-6e59-41c5-88d3-1aad4871f59c)

**Comment by rafaehlers** [comment]
Released in GV 2.31
