### ISSUE TITLE
Unable to search for users in the "Change Entry Creator" select field (since GV 2.30)

### ISSUE THREAD

**Issue by bennemann** [GravityKit/GravityView#2190]
When attempting to search for users in the "Change Entry Creator" select field, the AJAX request always produces an empty response, resulting in this message: "The results could not be loaded":

![image](https://github.com/user-attachments/assets/14f85d82-e0ff-47ef-bba2-ec0903216b72)

**Steps to Reproduce:**
1. Edit any entry in the Gravity Forms interface.
2. Attempt to search for a user in the "Change Entry Creator" select field.

I think this issue was introduced in commit [24f875b](https://github.com/GravityKit/GravityView/commit/24f875b8b1310b5f941fdb051e26e2a4833c617b).

The `wp_kses` function is stripping out the hidden `<input>` field that contains the nonce used for the AJAX request. 

As a result, the nonce verification fails, causing the request to die into an empty response.

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2752925566/58624

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2753414571/58643?folderId=408730

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2753414571/58643

**Comment by rafaehlers** [comment]
Customers were notified of the fix in GV 2.31 ✅
