### ISSUE TITLE
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated 

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2225]
>Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in C:\Users\rafae\Local Sites\gf29\app\public\wp-content\plugins\gravityview\future\includes\class-gv-permalinks.php on line 269

I don't know how to replicate it; this is only happening on one of my local websites.

Gravity Forms 2.9.0, GravityView 2.32, PHP 8.1.29, WP 6.7.1

[gk-migrate-gf29.local-2024-11-28-1732821039.zip](https://github.com/user-attachments/files/17952045/gk-migrate-gf29.local-2024-11-28-1732821039.zip)

![screencapture-gf29-local-catering-business-2024-11-28-17_08_12](https://github.com/user-attachments/assets/2cecbd97-ad1e-4fef-bf66-214085743e59)

**Comment by mrcasual** [comment]
It looks like @doekenorg also fixed it earlier in a PR: https://github.com/GravityKit/GravityView/pull/2222/commits/8c06b24504a874515fc124a7e8ed34b667df3510
