### ISSUE TITLE
Payment Status, Methods should `multiple` input type in Search Bar

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#516]
Generate an array of available options, generate auto-updated choices. Similar to entry creator functionality, except allowing radio/checkboxes/links.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995624897147273)

**Comment by soulseekah** [comment]
Related to https://github.com/gravityview/GravityView/issues/1188
