### ISSUE TITLE
Only show options in dropdown that are already selected in entries (sieve)

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#669]
For example, this drop down field in a Search Bar is displaying all countries where it should be displaying only the values that exist (are selected) in the submitted entries:

![gv-dropdown-countries](https://cloud.githubusercontent.com/assets/1222472/14186814/84515770-f756-11e5-8398-0fd329d6a6c0.jpg)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995638749481175)

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/189022681/5436/?folderId=408730

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/215982707/0/

**Comment by zackkatz** [comment]
This is close, could be released as a small plugin.

**Comment by rafaehlers** [comment]
Related: https://secure.helpscout.net/conversation/295481757/7728/?folderId=408730

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/556578006/14054?folderId=408730

**Comment by soulseekah** [comment]
I'll implement a filter at the very least, we can tie it into the UI later, right now there's no space for the UI.
By default filters for radios, dropdowns, multis will not be on. Standby.

**Comment by soulseekah** [comment]
The filter is called `gravityview/search/sieve_choices`.

Example:

```php
add_filter( 'gravityview/search/sieve_choices', function( $sieve, $filter, $context ) {
    if ( $context->view->ID == 4 && $filter['key'] == '6' ) {
        return true; // Only show used choices in entries for View ID 4 and Field ID 6
    }
    return $sieve;
}, 10, 3 );
```

Or:

```php
add_filter( 'gravityview/search/sieve_choices', '__return_true' ); // Sieve everything
```

![image](https://user-images.githubusercontent.com/685880/66203661-941c6700-e6b1-11e9-90e7-68965231d076.png)

**Comment by soulseekah** [comment]
@rafaehlers @jlgrisham see if you can test guys, it's a nice feature.

**Comment by zackkatz** [comment]
@soulseekah This looks like a very elegant solution! I would like to add an option into the UI, or perhaps have it on by default.

Thoughts about having it on by default?

**Comment by soulseekah** [comment]
I don't think showing it by default is the proper way to break things for everyone else :)

Filter, and then UI should be enough, I think. But support can have other ideas or preferenes.

**Comment by rafaehlers** [comment]
a UI option next to each field in the Search Bar modal will be great.

**Comment by zackkatz** [comment]
@soulseekah can you add options to the UI? I'll tweak once you add them.

**Comment by soulseekah** [comment]
> @soulseekah can you add options to the UI? I'll tweak once you add them.

Well we really need to work out how we're going to add these.
We have several search options (filters) and joins #1342 that need to be housed in the dialog box. We need to rethink the whole admin UI, which we discussed in our last team meeting. No steps were taken in that direction yet.
Do I just plop a checkbox with a long description of what it does next to each field? That wouldn't look good at all.

**Comment by rafaehlers** [comment]
Sieve choices aren't working for the Country drop down from the Address field (international) when added to the Search Bar:

https://user-images.githubusercontent.com/1222472/175651543-fab55b36-7f0f-408a-9536-654d72d834fe.mp4

Tested on GF 2.6.3.x and GV 2.14.6

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1923986544/41972

**Comment by zackkatz** [comment]
@rafaehlers Please let people know this is working now.
