### ISSUE TITLE
Add "Full width" field setting for Custom Content fields in single entry Table layouts

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#684]
This would allow the field to not have a `<th>` element by using `colspan="2"`

By limiting this to Custom Content fields, we avoid the "but…what about the labels" issue as referenced by Gennady below.

- Add a field setting for the value to span full width. This setting should only appear: 
    - In Custom Content fields
    - When in a Single Entry layout
- When enabled, hide the Custom Label setting
- In the template, add `colspan=2` to the output so that the value of the Custom Content field spans the full width of the table

**Comment by soulseekah** [comment]
What would this look like, I'm confused.

![image](https://user-images.githubusercontent.com/685880/69901317-e49e0100-1390-11ea-8040-72f12816ff44.png)

**Comment by zackkatz** [comment]
`colspan=2`

**Comment by soulseekah** [comment]
> `colspan=2`

This is not helpful, I've tried adding the attribute to the tr, the th and the td, it all looked messed up. What's the final table supposed to look like? Sorry :)

**Comment by soulseekah** [comment]
..boom! bump! bap!
