### ISSUE TITLE
Add a filter to disable Email Confirmation input in Edit Entry

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#714]
This is an exchange between me and a user:

> It seems that there is an issue with "Confirm Email" field. I mean, when you want to edit an entry "Confirm Email" field is always blank, so you need to always type again the email as confirm email is mandatory.

my answer:

> That's the "nature" of the Confirm Email field. Gravity Forms don't store the data typed on that field, it's probably just used for comparison against the other email field.

his reply:

> It makes complete sense wih Gravity Forms as you want to email field filled correctly.
> It does not make complete sense with Gravity View because entry is already correctly created.
> As a result, with Gravity View you have to fill email confirm field again and again and again. Or, you have to deactivate confirm email field but then you don´t benefil with confirmation field.

IMHO: if you want to edit the email, you need to make sure the new email is also right.

Related: https://secure.helpscout.net/conversation/203842687/5803/?folderId=408730

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995645590936869)

**Comment by zackkatz** [comment]
https://secure.helpscout.net/conversation/1023188790/23760/

**Comment by zackkatz** [comment]
I agree with the customer on this—it should at least be a View-wide setting.

**Comment by soulseekah** [comment]
This is similar to password fields. We have code in our edit entry that disregards passwords unless they have been changed, I think.

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2259839156/49507/

**Comment by mrcasual** [comment]
This can be done via a filter:

```php
add_filter( 'gravityview/edit_entry/field_value', function ( $field_value, $field ) {
	if ( 'email' === $field->type && $field->emailConfirmEnabled && isset( $field_value[ $field->id ] ) ) {
		$field_value = [
			$field_value[ $field->id ],
			$field_value[ $field->id ]
		];
	}

	return $field_value;
}, 10, 2 );
```

Alternatively, one can use `gform_pre_render` and disable `$field->emailConfirmEnabled`.

**Comment by rafaehlers** [comment]
https://docs.gravitykit.com/article/937-hiding-the-confirm-email-field-on-the-edit-entry-page
