### ISSUE TITLE
Upload fields don't store new uploads properly when there are validation errors

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#853]
Context: The Edit Entry screen with any required field and a file upload field.
If the user selects a file and submits the form while a required field is empty, the update will fail (as expected). 
However, when the page reloads, the file upload input **isn't cleared**. 
That leads to confusion as the file isn't available anymore and must be uploaded again to be saved:

To reproduce:

__Single File Upload Field:__

_This issue exists in 1.19.4_

1. Upload a file
2. Enter an error in a field
3. Save the form
4. The file appears uploaded 
5. Submit the form again
6. The file is no longer there

__Multiple File Upload Field:__

_This issue does not exist in 1.19.4_

1. Upload file
2. Enter an error in a field
3. Save the form
4. The file is no longer there

Links to examples:

- [Single file upload error](https://i.gravityview.co/IFx9/2ukmRoPn)
- [Multiple file upload error](https://i.gravityview.co/IuIr/5xyrvEjH)

Video: https://monosnap.com/direct/YbEjhxEoccpX2Kn7ePErSTEWBKreQX

**Comment by zackkatz** [comment]
Changes in Product fields are also not stored when there are validation errors.

**Comment by jakejackson1** [comment]
Ran into this problem today. Seems like GravityView is moving the uploaded files from their temporary home to the GF upload directory before the validation is done, instead of after. So when validation fails, Gravity Forms expects them to still be in the temporary folder and can't find them.

**Comment by aaronkine** [comment]
Following this thread in hopes of a fix.

**Comment by rafaehlers** [comment]
Related: https://github.com/gravityview/GravityView/issues/1695

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/2155642907/47010

**Comment by rafaehlers** [comment]
Still happening on GFs 2.7.2 and GV 2.17.1

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/1818398060/40265
https://secure.helpscout.net/conversation/1880675598/41208

**Comment by rafaehlers** [comment]
This has been fixed within this [PR](https://github.com/GravityKit/GravityView/issues/2086).

The file upload input is now cleared adequately if validation fails.

![2024-10-02 18-20-04](https://github.com/user-attachments/assets/f15f45fd-c384-4797-9a31-395435276e0e)

Customers notified ✅
