### ISSUE TITLE
Move Form Presets to an admin page

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#883]
Instead of having the presets inline in the View Configuration screen, move to its own page where people can explore what templates they want. When clicking a template, it will create a View from that template.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995654437212752)

**Comment by soulseekah** [comment]
Weren't we deprecating form presets? Or was that XML-based form presets?

**Comment by soulseekah** [comment]
I have insufficient permissions to create a new repository, @zackkatz 

![image](https://user-images.githubusercontent.com/685880/68031169-240efa00-fccc-11e9-9dab-361120767625.png)

Please create a `gravityview-presets` repository (or whatever you want it called). Thanks.

**Comment by zackkatz** [comment]
Called Presets. @soulseekah

**Comment by soulseekah** [comment]
@jlgrisham can you please test the https://github.com/gravityview/GravityView/archive/feature/remove-presets.zip branch a bit, please?

Let me know if you see anything that crashes, acts weirdly, etc.

**Comment by soulseekah** [comment]
The functionality will be moved here: https://github.com/gravityview/Presets
